#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

# ############################################################################ #
# #                                 APPLICATIONS                             # #
# ############################################################################ #

# Polybar
$HOME/.config/polybar/launch.sh

# Sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# ############################################################################ #
# #                                 RULE                                     # #
# ############################################################################ #

bspc rule -a Gimp desktop='^8' state=floating follow=on

# ############################################################################ #
# #                                 CONFIG                                   # #
# ############################################################################ #

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
